defaults: &defaults
  docker:
    - image: circleci/node:11.7

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install Dependencies
          command: npm ci
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Lint
          command: npm run lint
      - run:
          name: Build
          command: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - dist
      - persist_to_workspace:
          root: .
          paths:
            - node_modules
  semver:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Dist Folder
          command: node_modules/.bin/ts-node scripts/publish-prep.ts
      - run:
          name: Semantic Release
          command: node_modules/.bin/semantic-release

workflows:
  version: 2
  build:
    jobs:
      - build
      - semver:
          requires:
            - build
          filters:
            branches:
              only: master